version = "2.4"
style = "basic"
ignore_list = [".venv/**/*"]
namespace_default = "private"

[[languages]]
name = "Koka"
identifiers = ["koka"]
comment = {"open" = "//"}

[[languages]]
name = "C3"
identifiers = ["c3"]
comment = {"open" = "//"}

[hook.repl.Lisp]
command = "scheme --eedisable"
first_prompt = "> "
change_prompt = '(waiter-prompt-string "{key}>")'
prompt = "{key}> "
